---
extends: default

rules:
  new-lines:
    level: warning
    type: unix
  line-length:
    max: 500
  comments:
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926
  document-start:
    present: false
  document-end:
    present: false
  truthy:
    check-keys: false # otherwise fails on github actions
